services:
  frontend:
    image: roybarak1/invoice-angular-app:latest
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    image: node:18
    working_dir: /app
    command: bash -c "npm install && node server.js"
    volumes:
      - ./db.json:/app/db.json
      - ./server.js:/app/server.js
      - ./package.json:/app/package.json
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge